import Head from "next/head";
import Image from "next/image";
import AccessAlarmIcon from "@mui/icons-material/AccessAlarm";
import Header from "../components/homePage/Header";
import Nav from "../components/homePage/Nav";
import Banner from "../components/homePage/Banner";
import PromoContainer from "../components/homePage/PromoContainer";
import Footer from "../components/homePage/Footer";
import ListArticle from "../components/homePage/ListArticle";
import SideCart from "../components/SideCart";
import { useDispatch, useSelector } from "react-redux";
import { cartStatus } from "../redux/layoutSlice";
import { setCartOpen } from "../redux/layoutSlice";


export default function Home({ data }) {

  const CartisOpen=useSelector(cartStatus)

  const dispatch=useDispatch()
  const ChangeCartStatus=()=>{dispatch(setCartOpen())

  }

  return (
    <div className="flex ">
      <div className={` order-2  ${!CartisOpen ? " hidden":" block"} `}>
    <SideCart />
      </div>
     
<div className="flex flex-col bg-[#eaeded] flex-grow ">
      <Head>
        <title>
          Amazon.fr : livres,DVD,jeux Videos,musique,high tech,informatique
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* header */}
      <Header ChangeCartStatus={ChangeCartStatus}/>
      {/* Nav */}
      <Nav />
      <div className="max-w-screen-2xl mx-auto">
        {/* carousel */}
        <Banner />
        {/* Proposition category */}
        <div className="md:px-4 m-auto ">
          <PromoContainer />
          <ListArticle data={data }/>
        </div>
      </div>

      {/* Selections: Les plus demandés des jeux videos */}

      {/* Selections: Jeansles plus aprecies des homes*/}

      {/* Category autres */}

      {/*  */}
      {/* Footer */}
      <Footer />
    </div>
    </div>
    
  );
}

export async function getServerSideProps(context) {
  const DataFetch = await fetch(
    // "https://api.escuelajs.co/api/v1/products?offset=0&limit=5"
    'https://fakestoreapi.com/products?limit=8'
  );
  const data = await DataFetch.json();

  return {
    props: { data: data }, // will be passed to the page component as props
  };
}
